import {
  SavedFileRole,
  ToolId,
  ToolPreviewKind,
  ToolSelectionMode,
  ToolWorkflowKind,
} from '../types/models';

export type ToolCategory = 'Optimize' | 'Convert' | 'Assemble' | 'Extract';

export type ToolDefinition = {
  id: ToolId;
  title: string;
  description: string;
  shortLabel: string;
  icon: string;
  category: ToolCategory;
  accepts: 'images' | 'pdf' | 'docx' | 'pdfs' | 'ocr-sources';
  workflowKind: ToolWorkflowKind;
  previewKind: ToolPreviewKind;
  selectionMode: ToolSelectionMode;
  supportsReorder: boolean;
  supportsCompare: boolean;
  supportsPagePreview: boolean;
  defaultOutputKind: SavedFileRole;
  optionSchema: string[];
};

export const toolDefinitions: ToolDefinition[] = [
  {
    id: 'ocr-searchable',
    title: 'OCR to Searchable PDF',
    shortLabel: 'OCR Searchable PDF',
    icon: 'text-recognition',
    description: 'Recognize text offline from images or PDFs, then save searchable PDFs or plain text.',
    category: 'Convert',
    accepts: 'ocr-sources',
    workflowKind: 'ocr-sources',
    previewKind: 'filmstrip',
    selectionMode: 'multiple',
    supportsReorder: false,
    supportsCompare: false,
    supportsPagePreview: true,
    defaultOutputKind: 'pdf',
    optionSchema: ['ocrScript', 'ocrOutput'],
  },
  {
    id: 'compress-images',
    title: 'Compress Images',
    shortLabel: 'Compress Images',
    icon: 'image-outline',
    description: 'Reduce image size while keeping text readable for office work.',
    category: 'Optimize',
    accepts: 'images',
    workflowKind: 'image-batch',
    previewKind: 'compare',
    selectionMode: 'multiple',
    supportsReorder: true,
    supportsCompare: true,
    supportsPagePreview: false,
    defaultOutputKind: 'compressed',
    optionSchema: ['compressionPreset'],
  },
  {
    id: 'compress-pdf',
    title: 'Compress PDF',
    shortLabel: 'Compress PDF',
    icon: 'file-percent-outline',
    description: 'Optimize scanned PDFs offline with balanced or visually lossless compression.',
    category: 'Optimize',
    accepts: 'pdf',
    workflowKind: 'pdf-pages',
    previewKind: 'filmstrip',
    selectionMode: 'multiple',
    supportsReorder: false,
    supportsCompare: true,
    supportsPagePreview: true,
    defaultOutputKind: 'compressed',
    optionSchema: ['compressionPreset', 'pageSize'],
  },
  {
    id: 'image-cleanup',
    title: 'Image Cleanup',
    shortLabel: 'Image Cleanup',
    icon: 'image-edit-outline',
    description: 'Clean up imported images using Kaagaz document enhancement filters.',
    category: 'Optimize',
    accepts: 'images',
    workflowKind: 'image-batch',
    previewKind: 'compare',
    selectionMode: 'multiple',
    supportsReorder: true,
    supportsCompare: true,
    supportsPagePreview: false,
    defaultOutputKind: 'image',
    optionSchema: ['cleanupMode', 'compressionPreset'],
  },
  {
    id: 'images-to-pdf',
    title: 'Images to PDF',
    shortLabel: 'Images to PDF',
    icon: 'file-image-outline',
    description: 'Turn one or more images into a PDF with the selected page size.',
    category: 'Convert',
    accepts: 'images',
    workflowKind: 'image-batch',
    previewKind: 'filmstrip',
    selectionMode: 'multiple',
    supportsReorder: true,
    supportsCompare: false,
    supportsPagePreview: false,
    defaultOutputKind: 'pdf',
    optionSchema: ['pageSize', 'compressionPreset'],
  },
  {
    id: 'pdf-to-images',
    title: 'PDF to Images',
    shortLabel: 'PDF to Images',
    icon: 'image-multiple-outline',
    description: 'Render PDF pages as JPG or PNG files stored locally.',
    category: 'Convert',
    accepts: 'pdf',
    workflowKind: 'pdf-pages',
    previewKind: 'grid',
    selectionMode: 'multiple',
    supportsReorder: false,
    supportsCompare: false,
    supportsPagePreview: true,
    defaultOutputKind: 'image',
    optionSchema: ['outputFormat', 'compressionPreset'],
  },
  {
    id: 'pdf-to-docx',
    title: 'PDF to DOCX',
    shortLabel: 'PDF to DOCX',
    icon: 'file-word-outline',
    description: 'Build a scan-friendly DOCX with each PDF page inserted as an image.',
    category: 'Convert',
    accepts: 'pdf',
    workflowKind: 'pdf-pages',
    previewKind: 'filmstrip',
    selectionMode: 'multiple',
    supportsReorder: false,
    supportsCompare: false,
    supportsPagePreview: true,
    defaultOutputKind: 'docx',
    optionSchema: ['pageSize', 'compressionPreset'],
  },
  {
    id: 'docx-to-pdf',
    title: 'DOCX to PDF',
    shortLabel: 'DOCX to PDF',
    icon: 'file-pdf-box',
    description: 'Convert Kaagaz or image-based DOCX files into PDFs without the internet.',
    category: 'Convert',
    accepts: 'docx',
    workflowKind: 'docx-pages',
    previewKind: 'filmstrip',
    selectionMode: 'multiple',
    supportsReorder: false,
    supportsCompare: false,
    supportsPagePreview: true,
    defaultOutputKind: 'pdf',
    optionSchema: ['pageSize', 'compressionPreset'],
  },
  {
    id: 'pdf-merge',
    title: 'PDF Merger',
    shortLabel: 'Merge PDFs',
    icon: 'file-multiple-outline',
    description: 'Combine multiple PDFs into one local output file.',
    category: 'Assemble',
    accepts: 'pdfs',
    workflowKind: 'pdf-documents',
    previewKind: 'document-stack',
    selectionMode: 'multiple',
    supportsReorder: true,
    supportsCompare: false,
    supportsPagePreview: true,
    defaultOutputKind: 'merged',
    optionSchema: ['compressionPreset'],
  },
  {
    id: 'pdf-reorder',
    title: 'PDF Reorder / Rotate',
    shortLabel: 'Reorder PDF',
    icon: 'swap-vertical',
    description: 'Reorder or rotate PDF pages and save a cleaned copy.',
    category: 'Assemble',
    accepts: 'pdf',
    workflowKind: 'pdf-pages',
    previewKind: 'filmstrip',
    selectionMode: 'multiple',
    supportsReorder: true,
    supportsCompare: false,
    supportsPagePreview: true,
    defaultOutputKind: 'pdf',
    optionSchema: ['rotateDegrees'],
  },
  {
    id: 'batch-rotate',
    title: 'Batch Rotate Images',
    shortLabel: 'Rotate Images',
    icon: 'rotate-right',
    description: 'Rotate several images at once and save new copies.',
    category: 'Assemble',
    accepts: 'images',
    workflowKind: 'image-batch',
    previewKind: 'grid',
    selectionMode: 'multiple',
    supportsReorder: true,
    supportsCompare: true,
    supportsPagePreview: false,
    defaultOutputKind: 'image',
    optionSchema: ['rotateDegrees', 'compressionPreset'],
  },
  {
    id: 'pdf-extract',
    title: 'Extract PDF Pages',
    shortLabel: 'Extract Pages',
    icon: 'content-cut',
    description: 'Extract a selected page range into a new PDF file.',
    category: 'Extract',
    accepts: 'pdf',
    workflowKind: 'pdf-pages',
    previewKind: 'grid',
    selectionMode: 'multiple',
    supportsReorder: true,
    supportsCompare: false,
    supportsPagePreview: true,
    defaultOutputKind: 'pdf',
    optionSchema: ['compressionPreset'],
  },
  {
    id: 'extract-first-page',
    title: 'Extract First Page',
    shortLabel: 'First Page Image',
    icon: 'numeric-1-box-outline',
    description: 'Save the first page of a PDF as an image for quick reuse.',
    category: 'Extract',
    accepts: 'pdf',
    workflowKind: 'pdf-pages',
    previewKind: 'compare',
    selectionMode: 'single',
    supportsReorder: false,
    supportsCompare: false,
    supportsPagePreview: true,
    defaultOutputKind: 'image',
    optionSchema: ['outputFormat', 'compressionPreset'],
  },
  {
    id: 'scan-to-jpg',
    title: 'Scan to JPG',
    shortLabel: 'Scan to JPG',
    icon: 'file-image-outline',
    description: 'Export cleaned scan pages as JPG images ready for sharing.',
    category: 'Extract',
    accepts: 'images',
    workflowKind: 'scan-pages',
    previewKind: 'filmstrip',
    selectionMode: 'multiple',
    supportsReorder: true,
    supportsCompare: false,
    supportsPagePreview: false,
    defaultOutputKind: 'image',
    optionSchema: ['compressionPreset'],
  },
];

export function getToolDefinition(toolId: ToolId) {
  return toolDefinitions.find((tool) => tool.id === toolId);
}
